name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  gh-pages-deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: rm -rf node_modules
      - run: yarn install --frozen-lockfile
      - run: git config user.name "Alisson Oliveira" && git config user.email "me@alisson.dev"
      - run: yarn deploy
